function [ ] = robust_hough_plot_lines( I, lines )
%ROBUST_HOUGH_PLOT_LINES plots hough lines into an image
%   ROBUST_HOUGH_PLOT_LINES (I, lines)
%   where I is the original image
%   and lines is the struct generated by robust_hough_lines that contains
%   the most dominant line segments.
colors = [ 4 0 0; 0 4 0; 0 0 4; 0 4 4; 4 0 4; 4 4 0; 0 2 2; 2 0 2; 2 2 0; 0 2 4; 4 2 0; 2 0 4; 0 4 2; 2 4 0; 4 0 2]/4;

hold off
imagesc(I);
colormap(gray(256));
hold on
for k=1:length(lines)
    [n1 n2] = size(lines(k).point1);
    for j=1:n1
        plot ([lines(k).point1(j,1) lines(k).point2(j,1)], [lines(k).point1(j,2) lines(k).point2(j,2)], '-', 'LineWidth', 4, 'Color', colors(mod(k,length(colors))+1,:));
end

end

